language: r
r:
  - bioc-release
  - bioc-devel
cache:
  packages: true
  directories:
  - docs
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::codecov()'
notifications:
  email:
    on_success: seandavi@gmail.com
    on_failure: seandavi@gmail.com
r_github_packages: hadley/pkgdown
script:
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: docs
